### ISSUE TITLE
Bijector error during data transformation in Turing

### ISSUE THREAD

**Issue by itsdfish** [itsdfish/SequentialSamplingModels.jl#33]
In this [example](https://gist.github.com/itsdfish/0ba5aaf1681f2d8b52579773d830c103), Bijectors throws an error when the data are transformed inside the main loop of the Turing model. The last example in #31 shows a workaround.

**Comment by DominiqueMakowski** [comment]
On a user-experience note: 
The fact that one needs to pass a `data` object to the model formatted differently (as a tuple of individual tuples) than the `data` object expected by the SSM distributions (as a tuple of vector) makes it feel a bit clunky.
I wonder if it would not be easier to (additionally) allow for an independent specification of choice and rt in the distributions. For instance, add the `rt=none` keyword arguments to `LBA(data; **kwargs)`, and in case `data` is a vector (i.e., someone just passed `choice` alone) & `rt != none`, we just re-format `data = (choice=data, rt=rt)` as a first step in the function.

This would give some flexibility and hopefully make the practical usage smoother (also it would remove the need to do extra data transformation to make a vector of tuples)

**Comment by DominiqueMakowski** [comment]
Wait no actually no this wouldn't work since we need something that can be indexed in the `for i in n` loop of Turing... Okay nevermind then

**Comment by itsdfish** [comment]
@DominiqueMakowski, no problem. These things can be a bit tricky. The convention I adopted with NamedTuples follows the same convention used throughout Distributions.jl. For example, `rand(Normal())` returns a scalar while `rand(Normal(), 1)` returns a vector. In this package, we return a NamedTuple of scalars for `rand(LBA())` and a NamedTuple of vectors for `rand(LBA(), 1)`. 

You are right that the lack of indexing in the case of vectors is inconvenient. I did consider using a 2D array of floats instead, but the potential problem is that the choice indices are actually integers, and are often used for logical indexing `(e.g. [rt[choice .==1])`. Unfortunately, logical indexing could potentially fail due to float point error. I'm not sure how likely it would be in the scope of these models, but it could potentially create a silent bug which could invalidate someone's analyses. Depending on what you are doing, destructuring the NamedTuple can convenient, e.g., `choice,rt = rand(LBA(), n)` . As shown the doc strings, this works with broadcasting. Although the system is not perfect, I think some degree of pre-processing  of data is almost unavoidable.  

By the way, if you want a simpler way to generate a vector of NamedTuples, you can use a list comprehension or map:

```
n_obs =50
data1 = [rand(LBA(ν=[3.0, 2.0], A=0.8, k=0.2, τ=0.3)) for _ ∈ 1:n_obs]
data2 = [rand(LBA(ν=ν=[1.0, 1.5], A=0.8, k=0.2, τ=0.3)) for _ ∈ 1:n_obs]
data = vcat(data1, data2)
```

**Comment by DominiqueMakowski** [comment]
I think we can close this

**Comment by itsdfish** [comment]
I think there still might be a bug in Turing or Bijectors. We circumvented the problem by writing better code, but it seemed to be performing an unnecessary transformation. When I have time, I still raise the issue with devs at Turing.
