### ISSUE TITLE
LNR: vector of SDs

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#45]
Few questions:

- Similar to LBA, can we enable dual SDs in LNR?
- Minor: Consider renaming the https://github.com/itsdfish/SequentialSamplingModels.jl/blob/master/src/LogNormalRace.jl file by LNR.jl for consistency 
- In general, how much do you think there is room for optimizing (i.e., making faster) the code for the models (for instance for the logpdf calculation)? Would that impact sampling time or would that be marginal compared to the impact of AD?

**Comment by itsdfish** [comment]
@DominiqueMakowski, yes, yes and maybe. Those are good suggestions and I will push a commit in the next day or two. 

My suspicion is that choice of AD will have the largest impact on gradient-based samplers. In the benchmarks I performed on the LBA, Enzyme.jl was about 25x to 30x faster compared to ReverseDiff.jl using sample sizes of  10,100,and1000. A better comparison will vary the number of parameters. The problem I have run into so far is that `MvNormal` and `Dirichlet` do not currently work with Enzyme. I'll continue looking for a way to test Enzyme's scalability.
