### ISSUE TITLE
LBA docs minor

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#49]
Minor: the σ  parameters does not seem to be documented: https://itsdfish.github.io/SequentialSamplingModels.jl/dev/lba/ in the constructor, is this expected? 

Also, side question, is it possible to fit an LBA with only one accumulator? Say to compare with a Wald model?

**Comment by itsdfish** [comment]
@DominiqueMakowski, thanks for reporting the error. I updated the docs. 

You can certainly use the LBA with one accumulator. It could be used to compare the Wald in a simple detection task.  I suspect they might be more difficult to distinguish, and it's not clear to me whether any differences between the models are due only to auxiliary assumptions. But that has been a debate for a while. 

Here is an example:

```
using Plots 
using Random 
using SequentialSamplingModels

Random.seed!(5447)

dist = LBA(ν=[2.5], A = .8, k = .2, τ = .3) 
choice,rt = rand(dist, 10_000)

histogram(dist)
plot!(dist; t_range=range(.3, 2, length=100), xlims=(0, 2))
```
Note that there was a bug affecting the plot for LBA with 1 accumulator. You will need to update to 0.8.1 for the fix.

**Comment by DominiqueMakowski** [comment]
Amazing
