### ISSUE TITLE
Issue with pdf for WaldMixture

### ISSUE THREAD

**Issue by wrholmes82** [itsdfish/SequentialSamplingModels.jl#54]
I have been trying to use the WaldMixture in this SSM package. I am a long-time RT modeler, so I am familiar with both modeling and applications of these types of models. Here is the issue.

The "pdf" for the WaldMixture model does not actually produce a probability density function. That is, it does not produce a distribution that integrates to one (not even close for many parameters). For example, using parameters "v, sig, a, tnd = 3.0, 1.0, 2.0, 0.13;", the resulting density function integrates to ~1.31, and thus is not a pdf. The issue seems to be something with the drift variance since when sig=0.0, this problem goes away and it gets worse the larger sig becomes. I looked at the pdf code in src for this, and it seems to match the referenced paper, so not sure what is going on.

Here is some code that integrates and plots the appropriate pdf for different parameters using both the pdf built in here as well as a hand coded stochastic simulation pdf. Any thoughts? Am I doing something silly or is there an actual issue here?

```
using SequentialSamplingModels
using QuadGK
using Plots
using KernelDensity
using Distributions


#####
function Single_sim(v,a)

    dt = 0.001 # 1 ms
    sig_dt = 1.0 * sqrt(dt)

    Tfinal = 5.0;
    N_max = Int64(ceil(1.0/dt * Tfinal))

    x = 0.0
    thit = 1.0/eps(); # largest machine number
    for i = 1:N_max
        x = x + v*dt + randn() * sig_dt
        if x >= a
            thit = dt*i
            break
        end
    end

    return thit

end

#####
function WaldMixture_Nsim(v,σ,a,τ,Ns)

    vdist = Normal(v,σ);
    vvals = rand(vdist,Ns);

    rts = zeros(Ns)
    for i = 1:Ns
        rts[i] = Single_sim(vvals[i],a) + τ
    end

    return rts

end

v, sig, a, tnd = 3.0, 1.0, 2.0, 0.13; # Set parameters
dist = WaldMixture(v,sig,a,tnd); # Construct distribution
fun(x) = pdf(dist,x); # Generate pdf function to integrate
integral , error = quadgk(fun,tnd,5.0)  #Integrate

plotgrid = Vector(LinRange(tnd,5.0,1000)); # Set plot grid.
plotvals = pdf.(dist,plotgrid); # Evaluate WaldMixture on plot grid


#### Construct, integrate, and plot the pdf using stochastic simulation and density estimation.
Ns = 1_000_000; # Set number of simulations
rts = WaldMixture_Nsim(v,sig,a,tnd,Ns); # Simulate Ns wald accumulators
rts = rts[rts .< 1.0 / eps()]; # Remove any non-terminating rts
kde_rts = kde(rts,bandwidth = 0.0001); # Compute Kernel Density Estimate from data.
fun_kde(x) = pdf(kde_rts,x); # Construct a function to integrate and plot from kde.
integral , error = quadgk(fun_kde, tnd,5.0) # Integrate. 
plotvalskde = fun_kde.(plotgrid); # Evaluate kde distribution on plot grid.

# Plot "exact" and KDE approximation
plot(plotgrid,plotvals);
plot!(plotgrid,plotvalskde)
```

**Comment by DominiqueMakowski** [comment]
Quickly just piggybacking on this to mention that the Drift rate section is duplicated in the [docs](https://itsdfish.github.io/SequentialSamplingModels.jl/dev/wald_mixture/)

![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/d1e19732-ffd8-45ce-8273-0414f75be280)
