### ISSUE TITLE
LNR model makes off-scale predictions for 1-choice data?

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#60]
We finally started piloting a project (a cognitive control game) that I am excited to analyze using SSMs. We gathered a few participants for the first "level" of the game, which is a simple reaction time task where people just have to answer as fast as they can when something appears (no choice).

Out of curiosity, I fitted the 3 models to the whole data (not caring for now about the presence of multiple participants) that I think are compatible with 1 choice data; Wald, LNR and LBA.

However, the LNR model gives me way-off predictions, and I'm not sure if I did something wrong or what's going on (see PPcheck plot). Do you see anything obvious that I might have overlooked? 

Here's the reproducible code:

<details>
  <summary>Model Fitting</summary>

```julia
using CSV
using DataFrames
using Turing
using SequentialSamplingModels
using StatsPlots
using Pigeons
using GLMakie

# Read data
df = CSV.read(download("https://raw.githubusercontent.com/RealityBending/DoggoNogo/main/study1/data/data_game.csv"), DataFrame)

# Wald model
@model function model_wald(data; min_rt=minimum(data.rt))
    # Priors
    ν ~ truncated(Normal(5, 2), 0.0, Inf)
    α ~ truncated(Normal(.5, .4), 0.0, Inf)
    τ  ~ truncated(Normal(.2, .05), 0.0, min_rt)

    for i in 1:length(data)
        data[i] ~ Wald(; ν, α, τ)
    end
end

chain_wald = sample(model_wald(df.RT, min_rt=minimum(df.RT)), NUTS(), 1000)
# StatsPlots.plot(chain_wald; size=(600, 2000))
# summarystats(chain_wald)


# LBA model
@model function model_lba(data; min_rt=minimum(data.rt))
    ν ~ filldist(truncated(Normal(3, 5), 0.0, Inf), 1)
    σ ~ filldist(truncated(Normal(0, 1), 0.0, Inf), 1)
    A ~ truncated(Normal(0.4, 0.4), 0.0, Inf)
    k ~ truncated(Normal(0.2, 0.2), 0.0, Inf)
    τ ~ truncated(Normal(.2, .05), 0.0, min_rt)

    for i in 1:length(data)
        data[i] ~ LBA(; ν, σ, A, k, τ)
    end
end

dat = [(choice=1, rt=df.RT[i]) for i in 1:length(df.RT)]
chain_lba = sample(model_lba(dat, min_rt=minimum(df.RT)), NUTS(), 1000)


# LNR model
@model function model_lnr(data; min_rt=minimum(data.rt))
    ν ~ filldist(truncated(Normal(3, 5), 0.0, Inf), 1)
    σ ~ filldist(truncated(Normal(0, 3), 0.0, Inf), 1)
    τ ~ truncated(Normal(.2, .05), 0.0, min_rt)

    for i in 1:length(data)
        data[i] ~ LNR(; ν, σ, τ)
    end
end

chain_lnr = sample(model_lnr(dat, min_rt=minimum(df.RT)), NUTS(), 1000)
```
</details>

<details>
  <summary>Posterior Predictive Check</summary>

```julia
# PP Check
pred = predict(model_wald([missing for i in 1:100]; min_rt=minimum(df.RT)), chain_wald)
pred_rt_wald = Array(pred)[:, 2:2:end]

pred = predict(model_lba([(missing) for i in 1:100]; min_rt=minimum(df.RT)), chain_lba)
pred_rt_lba = Array(pred)[:, 2:2:end]

pred = predict(model_lnr([(missing) for i in 1:100]; min_rt=minimum(df.RT)), chain_lba)
pred_rt_lnr = Array(pred)[:, 2:2:end]

# Plot density
f = Figure()
ax1 = Axis(f[1, 1], title = "Wald")
for i in 1:size(pred_rt_wald)[2]
    lines!(ax1, Makie.KernelDensity.kde(pred_rt_wald[:, i]), color="green", alpha=0.05)
end
ax2 = Axis(f[2, 1], title = "LBA")
for i in 1:size(pred_rt_lba)[2]
    lines!(ax2, Makie.KernelDensity.kde(pred_rt_lba[:, i]), color="blue", alpha=0.05)
end
ax3 = Axis(f[3, 1], title = "LNR")
for i in 1:size(pred_rt_lnr)[2]
    lines!(ax3, Makie.KernelDensity.kde(pred_rt_lnr[:, i]), color="red", alpha=0.05)
end
GLMakie.xlims!(ax3, (0, 50))
for ax in [ax1, ax2]
    lines!(ax, Makie.KernelDensity.kde(df.RT), color="black")
    GLMakie.xlims!(ax, (0.15, 0.8))
end
f
```

</details>

![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/cd1297e3-01ab-4c7d-8049-d5b0be1ddb69)

**Comment by DominiqueMakowski** [comment]
PS: in the docs I think there's a typo with a "Plots" word inserted 
![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/921dc8ab-5cb0-4831-9760-53a6b8dc0fb5)

**Comment by itsdfish** [comment]
Thanks for reporting the error in the docs. I will fix that soon. 

One thing to keep in mind with the LNR is that the drift rate parameter has a different interpretation. It is the mean first passage time in log-space.  For this reason, the prior distribution for nu and sigma will need to be adjusted.  Here is something that appears to work better:


```
using CSV
using DataFrames
using Turing
using SequentialSamplingModels

df = CSV.read(download("https://raw.githubusercontent.com/RealityBending/DoggoNogo/main/study1/data/data_game.csv"), DataFrame)

# LNR model
@model function model_lnr(data; min_rt=minimum(data.rt))
    ν ~ filldist(Normal(-3, 1), 1)
    σ ~ filldist(truncated(Normal(.5, .5), 0.0, Inf), 1)
    τ ~ truncated(Normal(.2, .05), 0.0, min_rt)

    for i in 1:length(data)
        data[i] ~ LNR(; ν, σ, τ)
    end
end

dat = [(choice=1, rt=df.RT[i]) for i in 1:length(df.RT)]
```

chain_lnr = sample(model_lnr(dat, min_rt=minimum(df.RT)), NUTS(), 1000)

Note that I have removed the positive constraint on nu and made the mean of the prior negative. Setting up the prior in a principled fashion is challenging because mean RT depends on both nu and sigma, but I think what I have above is somewhat reasonable

**Comment by DominiqueMakowski** [comment]
The weird thing is that the posterior seems to reasonably converge, but still the predictions are still not quite on the scale, even with the above priors: 


![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/9d5aef76-201a-4bf0-bd7b-2e3b2d858ffd)

I tried widening the priors but the posteriors remains essentially the same (which suggests that the model is "correct" ?)

Could be a problem of link function that we need to log-pass the predictions or something like that?

**Comment by itsdfish** [comment]
@DominiqueMakowski, I did not see that you posted your plot code. Here is the problem:

`pred = predict(model_lnr([(missing) for i in 1:100]; min_rt=minimum(df.RT)),  chain_lba)`

You accidentally passed `chain_lba` instead of `chain_lnr`

**Comment by itsdfish** [comment]
I'll go ahead and close this issue for now. I'm fairly confident that was the issue last problem, but feel free to reopen if that is wrong. 

Good luck with your project. I hope you find something interesting!

**Comment by DominiqueMakowski** [comment]
Erf i overlooked this sorry for the false alert and thanks the fresh look at the code!

**Comment by itsdfish** [comment]
No problem! It happens to me too.
