### ISSUE TITLE
Minor docs

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#83]
![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/262abc0f-a579-4fcd-9650-fa14ff69e90f)

There is also a [typo](https://github.com/itsdfish/SequentialSamplingModels.jl/blob/master/ext/plots/plot_model.jl#L61) in this function (extra "a").

Sorry I keep bumping you with these :)

**Comment by DominiqueMakowski** [comment]
![image](https://github.com/itsdfish/SequentialSamplingModels.jl/assets/8875533/9c5cf09e-ae35-42f9-b67c-30d8dd560459)

Another minor consistency suggestion for the title of the sections:

- Single Choice Models 
  - ExGaussian 
  - Shifted LogNormal
  - Shifted Wald
  - Mixture Wald


Also regarding Mixture Wald, am I right in understanding that it is a generalization of the Shifted Wald and that Mixture Wald == Shifted Wald when η=0?

**Comment by itsdfish** [comment]
No problem. These are all good suggestions. 

Regarding your question about the Mixture Wald, you are correct.

**Comment by DominiqueMakowski** [comment]
> Regarding your question about the Mixture Wald, you are correct.

Wouldn't it make sense to "merge" the two constructors to streamline the user-facing API? 
And internally use Wald when η=0 and MixtureWald when >0?
similarly to what the plan was in https://github.com/itsdfish/SequentialSamplingModels.jl/pull/29 for DDMs if I understood

**Comment by itsdfish** [comment]
I think that is something worth considering in the future.

**Comment by DominiqueMakowski** [comment]
Cool, I'll close this and will open a new issue to track that, so that I don't forget to update my docs if it's implemented

(the reason is that I am (once again) writing down my understanding of SSMs this time in a document for which I envision a larger scope: https://dominiquemakowski.github.io/CognitiveModels/4a_rt_descriptive.html

don't hesitate to let me know what you think and share any thoughts or ideas :) )   The way I see it, this "book" could be an add-on to this package where that could serve as a gentle general introduction to SSMs, from which people would then be able to make the most out of the more specific and technical examples of this package's documentation)
