### ISSUE TITLE
Wald: issues at drift=0

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#93]
My Wald models often have convergence issues, with:

```
ERROR: TaskFailedException

    nested task error: TaskFailedException

        nested task error: DomainError with Dual{ForwardDiff.Tag{DynamicPPL.DynamicPPLTag, Float64}}(0.0,0.0,0.0,0.0,0.0,0.0):
        InverseGaussian: the condition μ > zero(μ) is not satisfied.
        Stacktrace:
```

**despite** having the drift specified on the log-link. (And then `exp()` before being passed to Wald).

I suspect this is because: `logpdf(Wald(0.0, 1, 1), 80.0)` is `NaN` instead of `-Inf`.

**Comment by itsdfish** [comment]
I think I can return -Inf for nu = 0. The source of the NaN is found here: https://github.com/itsdfish/SequentialSamplingModels.jl/blob/ec1484e0e28ccd2fde156b97dc61129b278b2e00/src/Wald.jl#L57C35-L57C44

Are you having trouble with Turing or Pigeons? The reason I ask is that Pigeons is finicky about -Inf and will throw an error.

**Comment by DominiqueMakowski** [comment]
The problem was with Turing, for Pigeons I'll try later ([it has potentially been improved](https://github.com/Julia-Tempering/Pigeons.jl/issues/245#issuecomment-2288667230)) ☺️ thanks!
