### ISSUE TITLE
Docs: ShiftedLogNormal: sigma in log space

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#95]
The [docs](https://itsdfish.github.io/SequentialSamplingModels.jl/dev/shifted_lognormal/) mention that sigma is expressed is in log-space but it doesn't look like it is:

```jl
rand(ShiftedLogNormal(-0.2, -0.2, 0.2), 10)
```

```
ERROR: DomainError with -0.2:
LogNormal: the condition σ ≥ zero(σ) is not satisfied.
Stacktrace:
 [1] #385
   @ C:\Users\domma\.julia\packages\Distributions\ji8PW\src\univariate\continuous\lognormal.jl:36 [inlined]
 [2] check_args
   @ C:\Users\domma\.julia\packages\Distributions\ji8PW\src\utils.jl:89 [inlined]
 [3] #LogNormal#384
   @ C:\Users\domma\.julia\packages\Distributions\ji8PW\src\univariate\continuous\lognormal.jl:36 [inlined]
 [4] LogNormal
   @ C:\Users\domma\.julia\packages\Distributions\ji8PW\src\univariate\continuous\lognormal.jl:35 [inlined]
 [5] rand(rng::TaskLocalRNG, dist::ShiftedLogNormal{Float64}, n_trials::Int64)
   @ SequentialSamplingModels C:\Users\domma\.julia\packages\SequentialSamplingModels\wbo4d\src\ShiftedLogNormal.jl:52
 [6] rand(s::ShiftedLogNormal{Float64}, dims::Int64)
   @ Distributions C:\Users\domma\.julia\packages\Distributions\ji8PW\src\genericrand.jl:22
 [7] top-level scope
   @ c:\Users\domma\Dropbox\RECHERCHE\Studies\DoggoNogo\study1\analysis\1_models_make.jl:129
```

**Comment by itsdfish** [comment]
Agreed. The wording is confusing.  In either case, the sigma parameter must be positive. The most important point is if X ~ lognormal(mu, sigma),  then log(X) ~ normal(mu', sigma').

**Comment by itsdfish** [comment]
Also, keep in mind that the parameters do not have a simple interpretation, unlike for a normal distribution. In a lognormal distribution, mu and sigma both affect the mean and standard deviation.

**Comment by itsdfish** [comment]
I updated the docs to have a neutral intepretation, but referred users to ACT-R if they want a more substantive interpretation of the parameters. I didn't go into detail, but here is the basic idea: From the theoretical perspective of ACT-R, mu is the mean activation of a memory chunk, which is intepreted as the log odds that a particular memory is needed. The parameter sigma controls the standard deviation of activation noise. In this case, we have activation a ~ normal(mu, sigma), and retrieval time t = exp(-a) is inversely related to activation, which means t ~ lognormal(-mu, sigma). So if you are modling a memory process, you could adopt that interpretation of the parameters.
