### ISSUE TITLE
Make sigma type flexible for LNR

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#96]
Just a quick question about LCA's sigma: https://itsdfish.github.io/SequentialSamplingModels.jl/dev/lca/#Diffusion-Noise

Is it always a fixed value for all accumulators or is it possible to have one per accumulator as-in LBA & LNR?

**Comment by itsdfish** [comment]
Hmmm. I'm not sure whether they should vary for any of the models due to risk of non-identifiability. My thinking is that we should perform a parameter recovery simulation or look to the literature.

**Comment by kiante-fernandez** [comment]
Within-trial noise per accumulator is a scaling constant varying per accumulator, which would lead to issues of interpretability and, more crucially, identifiability. Also for a nice recovery study on LCA see Miletić.

Miletić, S., Turner, B. M., Forstmann, B. U., & van Maanen, L. (2017). Parameter recovery for the Leaky Competing Accumulator model. Journal of Mathematical Psychology, 76(Part A), 25–50. [https://doi.org/10.1016/j.jmp.2016.12.001](https://psycnet.apa.org/doi/10.1016/j.jmp.2016.12.001)

**Comment by kiante-fernandez** [comment]
I mean, if you really wanted to vary it because you cared about how different stimuli might have varying amounts of noise, you would traditionally have to fix some other parameters along the way. However, even then, the examination of within-trial noise is usually done with relatively simpler model specifications, such as the DDM.

**Comment by itsdfish** [comment]
For the LNR, sigma can vary by accumulator (see equation 3). However, it might have an adverse effect on the variance or covariance of the posterior distributions. Its something that I have considered changing back to a single value. 


Rouder, J. N., Province, J. M., Morey, R. D., Gomez, P., & Heathcote, A. (2015). The lognormal race: A cognitive-process model of choice and latency with desirable psychometric properties. Psychometrika, 80, 491-513.

**Comment by itsdfish** [comment]
Upon further thought, I think one way to handle the LNR is to use something like the following:

```
struct S{T1 <:Real, T2 <: Union{<: T1, Vector{<: T1}}}
   x::T1
   y::T2 
end

s1 = S(1, [2])

s2 = S(1, 2)
```

This would provide a type stable way to use a scalar or vector for sigma. I"ll keep this open to implement that change.

**Comment by DominiqueMakowski** [comment]
I like the idea of having the possibility to have a scalar or a vector (for experimentation purposes).

I think it's okay to offer non-default options that are "bad" - especially if we mention them in the docs (for instance for LCA, sigma would be a scalar by default, but the docs could mention `"can also be a vector to specify different values for each accumulator, but note that it might lead to model convergence issues (see Miletić et al., 2017)"`), it would still be useful for research. In order to have a simulation study about the identifiability of some parameters specification you need to be able to specify them in the first place, so being flexible would make it useful for researchers on top of "casual users"

**Comment by itsdfish** [comment]
Agreed. I think the LNR is OK with mutiple sigma values even though the estimation properties might suffer. The main thing I don't want to do is to add vectors in cases where the parameters are unidentfiable or extremely problematic.
