### ISSUE TITLE
Docs improvement: write the domain of parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#97]
Something that would be useful to add in the documentation as well as the docstrings, on top of "typical range" as we discussed previously, would be the domain. Which parameters are defined [-Inf, Inf], which must be > 0, etc. This would be helpful for parametrization and would save some thinking and testing (especially when doing specifying lots of different types of models).

**Comment by kiante-fernandez** [comment]
Putting citations for studies looking at priors in the thread. Would the idea be to have a section in each model that gives those ranges/domains or just add to the explanation of each parameter?

Matzke, D., & Wagenmakers, E. J. (2009). Psychological interpretation of the ex-Gaussian and shifted Wald parameters: A diffusion model analysis. *Psychonomic Bulletin & Review, 16*, 798-817.

Tran, N. H., Van Maanen, L., Heathcote, A., & Matzke, D. (2021). Systematic parameter reviews in cognitive modeling: Towards a robust and cumulative characterization of psychological processes in the diffusion decision model. *Frontiers in Psychology, 11*, 608287.

**Comment by DominiqueMakowski** [comment]
> Would the idea be to have a section in each model that gives those ranges/domains or just add to the explanation of each parameter?

🤷  I think adding the info under each parameter section is fine (https://itsdfish.github.io/SequentialSamplingModels.jl/dev/wald/#Non-Decision-Time)

**Comment by itsdfish** [comment]
It might be useful to list the domain in the doc strings as a convienent reference, and inlclude details about priors in  the online documentation.
